name: burlingtonliving
favicon: null
layout_spectrum: 0.99746
typography_spectrum: 0.50338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000d13'
    - '#012d3a'
    - '#204653'
    - '#485155'
    - '#516d78'
  brandStrength: 0.13484340952709317
  lightness: 0.25
  saturation: 0.9350127035286278
  rhythmicContrast: 0.22261661011725664
purpose: []
