name: burlingtonliving
favicon: null
layout_spectrum: 0.28530461550690234
typography_spectrum: 0.27795566408894956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.13484340952709317
  lightness: 0.043890989385545254
  saturation: 0.9350127035286278
  rhythmicContrast: 0.22261661011725664
purpose: []
